### ISSUE TITLE
go chaincode should not be under a src directory

### ISSUE THREAD

**Issue by jt-nti** [IBM-Blockchain-Starter-Kit/chaincode-bootstrap#19]
Looking at the [hyperledger fabric tutorial](http://hyperledger-fabric.readthedocs.io/en/latest/chaincode4ade.html) and samples, and the [How to Write Go Code tutorial](https://golang.org/doc/code.html) it seems like this bootstrap repository shouldn't have its own `src` directory.

This repository should be under a `src` directory in a go workspace:
 
> The src subdirectory typically contains multiple version control repositories (such as for Git or Mercurial) that track the development of one or more source packages.

**Comment by jorgedr94** [comment]
@jt-nti  In the context of the pipeline we install and setup the go workspace. The src directory in the bootstrap code becomes the src directory of the go workspace.  So I think we have the right setup here. If we hadn't we would not even be able to compile go because the go command is quite picky about that structure.
